# Introduccion a NumPy

In [1]:
import numpy as np

In [4]:
# Crear un arreglo de 1 dimension con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print('Arreglo: ', arr1)
print('Formato: ', arr1.shape)
print('Tipo de datos: ', arr1.dtype)

Arreglo:  [1 2 3 4 5 6]
Formato:  (6,)
Tipo de datos:  int64


In [5]:
# Cambiar la forma del arreglo a una matriz de 2x3
arr2 = arr1.reshape((2,3))
print('Arreglo: ', arr2)
print('Formato: ', arr2.shape)
print('Tipo de datos: ', arr2.dtype)

Arreglo:  [[1 2 3]
 [4 5 6]]
Formato:  (2, 3)
Tipo de datos:  int64


In [7]:
# Crear una matriz (4,4) con numeros aleatorios entre 0 y 1
matrix = np.random.rand(4,4)
print('Arreglo: ', matrix)
print('Formato: ', matrix.shape)
print('Tipo de datos: ', matrix.dtype)

Arreglo:  [[0.45760285 0.75238778 0.32433015 0.75576703]
 [0.23829349 0.33242171 0.3577592  0.60061506]
 [0.1858468  0.49873844 0.67239319 0.88673138]
 [0.72337849 0.4624085  0.70197753 0.41947364]]
Formato:  (4, 4)
Tipo de datos:  float64


### Manipulacion de datos

In [3]:
# Crear un arreglo de dos dimensiones a partir de una lista de listas
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr, type(arr)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [5]:
# Crear un arreglo de ceros con una forma (3,4)
arr = np.zeros((3,4))
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# Crear un arreglo con unos con una forma (2,2)
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [12]:
arr[1,1] =10
arr

array([[ 1.,  1.],
       [ 1., 10.]])

In [13]:
# Crear una matriz identidad
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Crear un arreglo 3d de ceros con forma (2,3,4)
arr = np.zeros((2,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
arr[0,1,2] = 5
arr

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
arr = np.random.rand(2,5)
arr

array([[0.30101287, 0.47498001, 0.41820227, 0.99604155, 0.68405244],
       [0.54449635, 0.07502264, 0.81254348, 0.70306658, 0.77666564]])

In [18]:
arr.T

array([[0.30101287, 0.54449635],
       [0.47498001, 0.07502264],
       [0.41820227, 0.81254348],
       [0.99604155, 0.70306658],
       [0.68405244, 0.77666564]])

In [19]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [21]:
# concatenar arreglos horizontalmente 
arr_h = np.hstack((arr1,arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [23]:
# Concatenar de forma verticar
arr_v = np.vstack((arr1,arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Operaciones matematicas y estadisticas haciendo uso de arreglos

In [45]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [27]:
# Calcular la suma de los elementos
suma = np.sum(arr)
suma

15

In [29]:
# Calcular  el promedio de los elementos 
promedio = np.mean(arr)
promedio

3.0

In [35]:
mediana = np.median(arr)
mediana

3.0

In [36]:
# Calcular el producto de los elementos
producto = np. prod(arr)
producto

120

In [37]:
# Desviacion estandas 
desv_est = np.std(arr)
desv_est

1.4142135623730951

In [38]:
# Varianza
varianza = np.var(arr)
varianza

2.0

In [39]:
# Minimo de los elementos
minimo = np.min(arr)
minimo

1

In [41]:
# Maximo de los elementos
maximo = np.max(arr)
maximo 

5

In [42]:
# Calcular la suma acumulada
cumsum = np.cumsum(arr)
cumsum

array([ 1,  3,  6, 10, 15])

In [46]:
# Suma element-wise
arr + arr


array([ 2,  4,  6,  8, 10])

In [47]:
# Resta element-wise
arr - arr

array([0, 0, 0, 0, 0])

In [48]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [49]:
arr / arr

array([1., 1., 1., 1., 1.])